export const CREATE_ENTITY_INIT = `API/CREATE_ENTITY_INIT`
export const CREATE_ENTITY_SUCCESS = `API/CREATE_ENTITY_SUCCESS`
export const CREATE_ENTITY_FAILURE = `API/CREATE_ENTITY_FAILURE`

export const READ_ENTITY_INIT = `API/READ_ENTITY_INIT`
export const READ_ENTITY_SUCCESS = `API/READ_ENTITY_SUCCESS`
export const READ_ENTITY_FAILURE = `API/READ_ENTITY_FAILURE`

export const READ_ENTITY_LIST_INIT = `API/READ_ENTITY_LIST_INIT`
export const READ_ENTITY_LIST_SUCCESS = `API/READ_ENTITY_LIST_SUCCESS`
export const READ_ENTITY_LIST_FAILURE = `API/READ_ENTITY_LIST_FAILURE`

export const UPDATE_ENTITY_INIT = `API/UPDATE_ENTITY_INIT`
export const UPDATE_ENTITY_SUCCESS = `API/UPDATE_ENTITY_SUCCESS`
export const UPDATE_ENTITY_FAILURE = `API/UPDATE_ENTITY_FAILURE`

export const DELETE_ENTITY_INIT = `API/DELETE_ENTITY_INIT`
export const DELETE_ENTITY_SUCCESS = `API/DELETE_ENTITY_SUCCESS`
export const DELETE_ENTITY_FAILURE = `API/DELETE_ENTITY_FAILURE`